In [21]:
import pandas as pd
import numpy as np
import math
import csv
import re
from pyspark import SparkContext
from pyspark.sql import SQLContext
import pyspark.sql.functions 
from pyspark.sql import Row
from collections import OrderedDict



In [22]:
# # Q1 #

# # Des : In news data, count the words in two fields: ‘Title’ and ‘Headline’ respectively, 
# # and list the most frequent words according to the term frequency in descending order, 
# # in total, per day, and per topic, respectively

# # input data by using sqlContext, split data by comma, and use header as dataFrame column name
# df = sqlContext.read.format('com.databricks.spark.csv').options(header='true', inferschema='true', sep=',').load("file:/home/ethan/pythonwork/ipynotebook/HW2/HW2Data/News_Final.csv")


# def regAndKeyValue(collectData):
#     # regular expression setting
#     # "[a-zA-Z]+"
#     # key, value count 
#     wordCount = {}
#     orderResult = {}
#     Data = collectData.collect()
#     # retrivel all data from Title column
#     for i in range(len(collectData.collect())):
#         # split data by regular expression
#         ans = re.findall('[a-zA-z]+', str(Data[i][0]))
#         # key, value calculate
#         for w in ans:
#             if w not in wordCount:
#                 wordCount[w] = 1
#             else:
#                 wordCount[w] += 1
#     #print(wordCount)
#     orderResult = OrderedDict(sorted(wordCount.items(), key=lambda t: t[1], reverse=True))
#     #print(orderResult)
#     print(len(orderResult))
#     print("Done\n")


# # calculate Title and Headline Total key, value
# def total():
    
#     print("\t****** Starting processing total func ******")
    
#     # get column data from Titla column
#     columnData = ['Title','Headline']
    
#     for c in columnData:
#         title = df.select([c])
#         regAndKeyValue(title)
        
#     print("\t****** Processing total func Done!******\n\n")

    
# # calculate Title and Headline key, value by using topic
# def topic():
    
#     print("\t****** Starting processing topic func ******")
    
#     topic = ["obama","economy","microsoft","palestine"]
#     # get column data from Titla column
#     columnData = ['Title','Headline']
#     # retrivel columnData by four type topic
#     for c in columnData:
#         for i in range(4):
#             # filter data by topic and extract column data
#             topicData = df.filter(df['Topic']==topic[i]).select([c])
#             regAndKeyValue(topicData)
            
#     print("\t****** Processing topic func Done!******\n\n")

    
# # calculate Title and Headline key, value by using PublishDate
# def publishDate():
    
#     print("\t****** Starting processing day func ******\n")
#     # get column data from Titla column
#     columnData = ['Title','Headline']
#     date = df.select(['PublishDate']).collect()
#     flag = ""
#     wordCount = {}
#     orderResult = {}
#     # retrivel columnData by publishDate
#     for c in columnData:
#         # get column data
#         data = df.select([c]).collect()
#         # retrivel publishDate column
#         for d in range(len(data)):
#             # split publishData string by " "
#             day = date[d][0].split(" ")
#             # avoid error input
#             if len(day)==2:
#                 # split data by regular expression
#                 ans = re.findall('[a-zA-z]+', str(data[d][0]))
#                 # key, value calculate
#                 for w in ans:
#                     if w not in wordCount:
#                         wordCount[w] = 1
#                     else:
#                         wordCount[w] += 1            
#                 # when new date apeear then initital count dict
#                 if flag != day[0]:
#                     # sorting result
#                     orderResult = OrderedDict(sorted(wordCount.items(), key=lambda t: t[1], reverse=True))
#                     #print(len(orderResult))
#                     wordCount = {}
#                     orderResult = {}
#                     flag = day[0]
#         #print(c," processing done!\n")
                    
#     print("\t****** Processing day func Done!******\n\n")
    
    
# #total()
# #topic()
# publishDate()

print("\nQ1 done!\n")

# # Q1 #


Q1 done!



In [23]:
# # Q2 Done#

# Facebook = ["Facebook_Economy","Facebook_Microsoft","Facebook_Obama","Facebook_Palestine"]
# Google = ["GooglePlus_Economy","GooglePlus_Microsoft","GooglePlus_Palestine"]
# Linked = ["LinkedIn_Economy","LinkedIn_Microsoft","LinkedIn_Obama","LinkedIn_Palestine"]

# # processing Q2 request
# def process(file):
#     for f in file:
#         # input data from csv by using spark context
#         rdd = sc.textFile("file:/home/ethan/pythonwork/ipynotebook/HW2/HW2Data/"+f+".csv")
#         # remove header
#         header = rdd.first()
#         hrdd = rdd.filter(lambda x:x!= header)
        
#         # retrivel all dataset, each time calculate one row
#         for i in hrdd.take(rdd.count()):
#             ID =0  # for remove IDLink
#             perDaySum = 0  # for sum score
#             # split row data by split comma
#             for j in i.split(","):
#                 if ID !=0:
#                     perDaySum +=float(j)
#                 else:
#                     ID = float(j)
#             perDaySum = perDaySum - ID
#             #print("AveByHour :",perDaySum/48)
#             #print("AveByDay :",perDaySum/2)
#         print("Finish")
       
        
# #process(Facebook)
# #process(Google)
# #process(Linked)

print("\nQ2 done!\n")

# # Q2 #


Q2 done!



In [24]:
# # Q3 #
# topic = ["obama","economy","microsoft","palestine"]


# #rdd = pd.read_csv('file:/home/ethan/pythonwork/ipynotebook/HW2/HW2Data/News_Final.csv')

# # input data by using sqlContext, split data by comma, and use header as dataFrame column name
# df = sqlContext.read.format('com.databricks.spark.csv').options(header='true', inferschema='true', sep=',').load("file:/home/ethan/pythonwork/ipynotebook/HW2/HW2Data/News_Final.csv")

# # retrivel four topic
# for i in range(4):
#     print("\t******",topic[i],"******","\n")
#     # calculate total score under select topic
#     totalScore = df.filter(df['Topic']==topic[i]).select([sum('SentimentTitle')]).collect()
#     # calculate topic number
#     topicCount = df.filter(df['Topic']==topic[i]).count()
#     print(topic[i]+" TotalScore :",totalScore[0][0])
#     print(topic[i]+" AveScore :",totalScore[0][0]/topicCount,"\n")
#     print("\t******",topic[i],"******","\n\n")
    
# # Q3 #

    
print("\nQ3 done!\n")




Q3 done!



In [25]:
# Q4 #

# input data by using sqlContext, split data by comma, and use header as dataFrame column name
df = sqlContext.read.format('com.databricks.spark.csv').options(header='true', inferschema='true', sep=',').load("file:/home/ethan/pythonwork/ipynotebook/HW2/HW2Data/News_Final.csv")

# get topic
topic = ["obama","economy","microsoft","palestine"]
# get columnData
columnData = ['Title','Headline']

# calculate co-occurrence
def coOccurrence(termItem, Data):
    # initial co-occurrence matrix by using numpy
    coMatrix = np.zeros((100,100),int)
    # retrivel filter data
    for i in range(len(Data)):
        # split data by regular expression
        rowData = re.findall('[a-zA-z]+', str(Data[i][0]))
        # retrivel order term frequency list
        for t in range(100):
            # retrivel each row data
            if termItem[t] in rowData:
                # retirvel other keyword from order list
                for w in range(100):
                    # avoid compare to keyword itself, and calculate two keyword appear in rowData
                    if termItem[w] in rowData and termItem[w] is not termItem[t]:
                        coMatrix[t][w] += 1
    print(coMatrix)
    
    
# calculate termFrequency            
def termFrequency(Data):
    # save term frequency and order result
    wordCount = {}
    orderResult = {}
    # retrivel filter data
    #for i in range(len(Data))
    for i in range(len(Data)):
        # split data by regular expression
        rowData = re.findall('[a-zA-z]+', str(Data[i][0]))
        #key, value calculate
        for w in rowData:
            if w not in wordCount:
                wordCount[w] = 1
            else:
                wordCount[w] += 1
    # order term frequency
    orderResult = OrderedDict(sorted(wordCount.items(), key=lambda t: t[1], reverse=True))
    return orderResult
    # print(orderResult)

    
# main func
def main():
    for c in columnData:
        for t in range(4):
            print(c, "start processing task ",t)
            # filter data by using topic
            Data = df.filter(df['Topic']==topic[t]).select([c]).collect()
            #termFrequency(Data)
            orderTermFrequency = termFrequency(Data)
            # transfer OrderedDict to list
            termItem = list(orderTermFrequency)
            # process co-occurrence matrix
            coOccurrence(termItem, Data)
            
            print(c,"task ",t," processing done!")
            
# program start point
main()

        
print("\nQ1 done!\n")


# Q4 #

Title start processing task  0
[[   0 7655 6760 ...  225  210  217]
 [7655    0 1501 ...   76   48   42]
 [6760 1501    0 ...   47   53   48]
 ...
 [ 225   76   47 ...    0    1    6]
 [ 210   48   53 ...    1    0    3]
 [ 217   42   48 ...    6    3    0]]
Title task  0  processing done!
Title start processing task  1
[[   0 4398   19 ...  158  144  194]
 [4398    0 1399 ...   57   70  130]
 [  19 1399    0 ...   44   40   26]
 ...
 [ 158   57   44 ...    0    0   12]
 [ 144   70   40 ...    0    0    0]
 [ 194  130   26 ...   12    0    0]]
Title task  1  processing done!
Title start processing task  2
[[   0 4867 4104 ...  206  190  197]
 [4867    0  868 ...   59   41   38]
 [4104  868    0 ...   95   59   60]
 ...
 [ 206   59   95 ...    0    0    0]
 [ 190   41   59 ...    0    0    4]
 [ 197   38   60 ...    0    4    0]]
Title task  2  processing done!
Title start processing task  3
[[   0 1006  987 ...   48   39   33]
 [1006    0  348 ...    9    1   15]
 [ 987  348    0 ...  